import yargs, {Argv} from "yargs";

export function getYargs() {
    return yargs(process.argv.slice(2))
        .usage("Usage: $0 [options]")
        .wrap(null)
        .version(false);
}

export function addArguments(y:Argv<any>) {
    return y
        .options({
            "focus-project-candidate-search-data-directory": {
                type: "string",
                desc: "Path to the focus project candidate search data directory.",
                demandOption: true,
            },
            "focus-project-extract-data-directory": {
                type: "string",
                desc: "Path to the focus project extract data directory.",
                demandOption: true,
            },
            "locations-file-path": {
                type: "string",
                desc: "Path to the locations file generated by location generation.",
                demandOption: true,
            },
            "location-resolution-rules-file-path": {
                type: "string",
                desc: "Path to the location resolution rules file.",
                demandOption: true,
            },
            "output-directory": {
                type: "string",
                desc: "Path to the output directory.",
                demandOption: true,
            },
        });
}
