name: 900 - Process data

permissions:
  contents: write
  pull-requests: write

on:
  # run periodically
  schedule:
    - cron: '0 10 * * *'   # at 10:00 every day
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# do not run this workflow, when there's another instance is running for the same workflow
concurrency:
  group: 900-process-data
  # If this is enabled it will cancel current running and start latest
  cancel-in-progress: false

env:
  # workflow related
  BRANCH_NAME: 900-process-data
  ACTIONS_RUNNER_DEBUG: ${{ secrets.ACTIONS_RUNNER_DEBUG }}

jobs:
  job-900-process-data:
    name: run 900-process-data
    runs-on: ubuntu-latest

    steps:
      - name: Set env ENABLE_DEBUG_LOGGING
        run: |
          if [[ "${ACTIONS_RUNNER_DEBUG:-false}" == true ]]; then
            echo "LOG_LEVEL=debug" >> "$GITHUB_ENV"
          else
            echo "LOG_LEVEL=info" >> "$GITHUB_ENV"
          fi

      - uses: actions/setup-node@v3
        with:
          # TODO: use the nvmrc file
          node-version: 'lts/hydrogen'

      # if local actions testing, do not check out the branch
      - uses: actions/checkout@v4
        if: ${{ !github.event.act }} # skip during local actions testing
        with:
          fetch-depth: 500
          ref: ${{ env.BRANCH_NAME }}
      - uses: actions/checkout@v4
        if: ${{ github.event.act }} # skip during local actions testing

      - name: Print environment
        run: |
          node --version
          npm --version
          echo "GITHUB_WORKSPACE: ${{ github.workspace }}"
          echo "BRANCH_NAME: ${{ env.BRANCH_NAME }}"
          echo "ACTIONS_RUNNER_DEBUG: ${{ env.ACTIONS_RUNNER_DEBUG }}"
          echo "LOG_LEVEL: ${{ env.LOG_LEVEL }}"

      - name: Rebase onto main
        if: ${{ !github.event.act }} # skip during local actions testing
        run: |
          git config user.name "Ali Ok"
          git config user.email "aliok@redhat.com"
          git fetch origin
          git rebase origin/main --strategy-option=theirs
          git push --force origin ${{ env.BRANCH_NAME }}

      - name: Install dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

      - name: Start process
        run: |
          echo "Running on branch ${{ github.ref }}"
          echo "Running on commit ${{ github.sha }}"
          
          echo "Starting buildTruthMapsIndex"
          node "${{ github.workspace }}/dist/900-report-data-truthmap/buildTruthMapsIndex.js" \
            --focus-project-candidate-search-data-directory="${{ github.workspace }}/100-focus-project-candidate-search" \
            --focus-project-extract-data-directory="${{ github.workspace }}/200-focus-project-extract" \
            --focus-organization-details-data-directory="${{ github.workspace }}/210-focus-organization-details" \
            --locations-file-path="${{ github.workspace }}/250-location-generation/locations.json" \
            --location-resolution-rules-file-path="${{ github.workspace }}/900-report-data-truthmap/input-location-resolution-rules.json" \
            --user-and-contrib-search-data-directory="${{ github.workspace }}/400-user-and-contrib-search" \
            --output-directory="${{ github.workspace }}/900-report-data-truthmap"
          
          # TODO: sanity check for number of repos found in 210 and number of repos found in 200
          echo "Starting debugDataIndex"
          node "${{ github.workspace }}/dist/910-debug-data/debugDataIndex.js" \
            --user-count-search-data-directory="${{ github.workspace }}/300-user-count-search" \
            --user-and-contrib-search-data-directory="${{ github.workspace }}/400-user-and-contrib-search" \
            --report-data-truth-map-directory="${{ github.workspace }}/900-report-data-truthmap" \
            --output-directory="${{ github.workspace }}/910-debug-data"
          
          echo "Starting reportDataIndex"
          node "${{ github.workspace }}/dist/990-report-data/reportDataIndex.js" \
            --report-data-truth-map-directory="${{ github.workspace }}/900-report-data-truthmap" \
            --output-directory="${{ github.workspace }}/990-report-data"

      - name: Commit
        if: ${{ !github.event.act }} # skip during local actions testing
        run: |
          git add -A
          
          if [ -n "$(git status --porcelain)" ]; then
            echo "There are changes, committing and pushing."
            git commit -m "Automated - 900-process-data"
            git push --force origin ${{ env.BRANCH_NAME }}
          
            echo "Process is complete, creating a PR"
            # create the PR from a temporary branch
            AFFIX=$(date +%s) 
            TMP_BRANCH_NAME="${{ env.BRANCH_NAME }}-${AFFIX}"
            git checkout -b "${TMP_BRANCH_NAME}"
            git push --force origin "${TMP_BRANCH_NAME}"
            GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" gh pr create --title "[Automated] Report data" --body "Automated" --base main --head "${TMP_BRANCH_NAME}"
          fi
